### ISSUE TITLE
'Bot' object has no attribute 'notifyOnMessage'

### ISSUE THREAD

**Issue by RuBiCK** [mamcmanus/telegram-awslambda-bot-boilerplate#2]
If I test it locally, Bot has the attribute `notifyOnMessage` but running on lambda I get this error: `'Bot' object has no attribute 'notifyOnMessage'`
I think I meet all requisites because I installed packages from `requirements.txt` in the same directory where `bot.py` resides

Any clue about what could be happening?

**Comment by dfpoon** [comment]
I guess all the lines below "##FOR LOCAL DEV" in bot.py should be commented out when it is deployed to the AWS lambda. line 89: handle(event['message']) should be enough to handle the message in lambda.
